### ISSUE TITLE
No green light on "LOCAL BUILD"

### ISSUE THREAD

**Issue by hkxnyc** [learn-co-curriculum/ios-first-lab#5]
Hi -

I was able to finish the first lab after I setup Github on my windows.  The version that I installed is 1.9.6.github.0.
After I finished the lab, I get green light on the first and the third circle which are fork and pull request but I don't get the light on local build which is the middle one.  Is it because I am not using the XCode?
If then, is there anyway that I can continue with the next lecture?

Thank you so much!

**Comment by markedwardmurray** [comment]
You need to use Xcode for the iOS labs, which is only available from Apple on Mac computers running OS X. The latest major version (Xcode 7) is required for our labs, which can only be installed on Macs running OS 10.10 Yosemite or OS 10.11 El Capitan only.
