### ISSUE TITLE
Running local test in Xcode did not pass test in Learn

### ISSUE THREAD

**Issue by kenmhaggerty** [learn-co-curriculum/ios-first-lab#7]
Followed the instructions in step 4 of the lesson to run tests within Xcode by selecting Product -> Test, but doing so did not trigger a success notification ("green light") within learn.

![screen shot 2016-01-02 at 7 57 20 pm](https://cloud.githubusercontent.com/assets/2646968/12076828/458d0c7a-b18b-11e5-9d60-4b9dda9d1979.png)

**Comment by markedwardmurray** [comment]
hi ken, this usually means there was in issue with your environment setup. Use the Ask A Question button to get online help through Learn. Someone on staff can look up your machine's setup report through your profile.

**Comment by kenmhaggerty** [comment]
Hi Mark – I used the Ask A Question button but no one on staff responded (just another student it turns out). Could you just connect me with the appropriate person on staff?

**Comment by markedwardmurray** [comment]
@JimCampagno

**Comment by kenmhaggerty** [comment]
All good! Stopped into Flatiron School in person yesterday and Joe noticed
that xcpretty wasn't installed.

-Ken
